language: python
dist: bionic

matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    #- os: osx
    #  language: generic

#before_install:
#  - |
#    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
#      brew update || brew update
#      brew install libmagic
#      # The following wasn't required in the past and therefore may become
#      # obsolete once again in the future. Let's wait and see.
#      wget https://bootstrap.pypa.io/get-pip.py
#      sudo python get-pip.py
#      sudo pip install virtualenv
#      virtualenv $HOME
#      source $HOME/bin/activate
#    fi

install:
  - pip install -e .
  - pip install --upgrade pytest pytest-cov codecov coveralls mock

script:
  - '[[ $TRAVIS_OS_NAME == "linux" ]] && sudo apt update'
  - '[[ $TRAVIS_OS_NAME == "linux" ]] && sudo apt -y install p7zip-full rar unace-nonfree cabextract'
  - 'pytest --cov=sflock --cov-append'

  - python -c 'import sflock, sys ; assert "pkg_resources" not in sys.modules'

after_success:
  - codecov
  - coveralls
