name: build

env:
  COLUMNS: 132

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11" , "3.12", "3.13" ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: ./.github/actions/python-setup/
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run unit tests
        run: poetry run python -m pytest tests/
